# ARG BASE_IMAGE, bir önceki Dockerfile'dan otomatik olarak alınır.
ARG BASE_IMAGE
FROM ${BASE_IMAGE}

# Gerekli bağımlılıkların kurulumu (libavresample-dev -> libswresample-dev olarak düzeltildi)
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential cmake git wget unzip yasm pkg-config \
    libswscale-dev libgtk2.0-dev libtbb-dev libavcodec-dev \
    libavformat-dev python3-dev python3-numpy libjpeg-dev \
    libpng-dev libtiff-dev libswresample-dev libgoogle-glog-dev \
    libgflags-dev libgphoto2-dev libeigen3-dev libhdf5-dev \
 && rm -rf /var/lib/apt/lists/*

# Derlenecek OpenCV sürümü
ENV OPENCV_VERSION=4.x

RUN git clone --branch ${OPENCV_VERSION} --depth 1 https://github.com/opencv/opencv.git /tmp/opencv \
 && git clone --branch ${OPENCV_VERSION} --depth 1 https://github.com/opencv/opencv_contrib.git /tmp/opencv_contrib

# Derleme dizinini oluştur ve derlemeyi başlat
WORKDIR /tmp/opencv/build

RUN cmake \
        -D CMAKE_BUILD_TYPE=RELEASE \
        -D CMAKE_INSTALL_PREFIX=/usr/local \
        -D OPENCV_EXTRA_MODULES_PATH=/tmp/opencv_contrib/modules \
        -D WITH_CUDA=ON \
        -D WITH_CUDNN=ON \
        -D OPENCV_DNN_CUDA=ON \
        -D ENABLE_FAST_MATH=1 \
        -D CUDA_FAST_MATH=1 \
        -D WITH_CUBLAS=1 \
        -D CUDA_ARCH_BIN=8.6 \
        -D OPENCV_ENABLE_NONFREE=ON \
        -D BUILD_EXAMPLES=OFF \
        -D BUILD_TESTS=OFF \
        -D BUILD_PERF_TESTS=OFF \
        -D WITH_TBB=ON \
        -D BUILD_opencv_sfm=OFF \
        .. \
 && make -j$(nproc) \
 && make install \
 && ldconfig \
 && rm -rf /tmp/opencv /tmp/opencv_contrib