ARG BASE_IMAGE
FROM $BASE_IMAGE

# Custom OpenCV CUDA build
RUN apt-get update && apt-get install -y \
    build-essential cmake git libgtk2.0-dev pkg-config \
    libavcodec-dev libavformat-dev libswscale-dev \
    python3-dev python3-numpy

RUN git clone -b 4.9.0 https://github.com/opencv/opencv.git /tmp/opencv \
    && git clone -b 4.9.0 https://github.com/opencv/opencv_contrib.git /tmp/opencv_contrib \
    && mkdir /tmp/opencv/build && cd /tmp/opencv/build \
    && cmake \
       -D CMAKE_BUILD_TYPE=Release \
       -D CMAKE_INSTALL_PREFIX=/usr/local \
       -D OPENCV_EXTRA_MODULES_PATH=/tmp/opencv_contrib/modules \
       -D WITH_CUDA=ON \
       -D WITH_CUDNN=ON \
       -D CUDA_ARCH_BIN=8.6 \
       -D BUILD_opencv_cudacodec=OFF \
       .. \
    && make -j16 && make install \
    && ldconfig \
    && rm -rf /tmp/opencv /tmp/opencv_contrib